version: '2'
services:
  
  dash-proxy:
      image: pure/simple-reverse-proxy
      networks:
        - backend
        - app
      environment:
        UPSTREAM: app:4201
        VIRTUAL_PORT: 80
        HTTPS_METHOD: noredirect
        VIRTUAL_HOST: im-angular.live
        LETSENCRYPT_HOST: im-angular.live
        LETSENCRYPT_EMAIL: eamil@gmail.com
        
  app:
     image: node:12.14
     working_dir: /app/projects/wp-maps-app
     networks:
       - app
     environment:
       PORT: 4201
     command:
       - npm
       - run-script
       - prod
     volumes:
       - app_data:/app
 



networks:
  app:
  backend:
    external:
      name: proxy_backend

volumes:
  app_data:
    driver: local
